/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;

/**
 *
 * @author deadg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        ItemMnuCliente = new javax.swing.JMenuItem();
        ItemMnuFilme = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        ItemMnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        MenuArquivo.setText("Arquivo");

        ItemMnuCliente.setText("Cliente");
        ItemMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMnuClienteActionPerformed(evt);
            }
        });
        MenuArquivo.add(ItemMnuCliente);

        ItemMnuFilme.setText("Filme");
        MenuArquivo.add(ItemMnuFilme);

        jMenuBar2.add(MenuArquivo);

        MenuSair.setText("Sair");

        ItemMnuSair.setText("Sair");
        ItemMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMnuSairActionPerformed(evt);
            }
        });
        MenuSair.add(ItemMnuSair);

        jMenuBar2.add(MenuSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMnuSairActionPerformed
     this.dispose();
    }//GEN-LAST:event_ItemMnuSairActionPerformed

    private void ItemMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMnuClienteActionPerformed
      ClienteView cliente = new ClienteView();
      pnl_principal.removeAll();
      pnl_principal.add(cliente);
      pnl_principal.updateUI();
    }//GEN-LAST:event_ItemMnuClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMnuCliente;
    private javax.swing.JMenuItem ItemMnuFilme;
    private javax.swing.JMenuItem ItemMnuSair;
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
